[package]
name = "egistream"
version = "0.1.0"
authors = ["sKyrBBit <iamskyrabbit@gmail.com>"]
edition = "2018"

[dependencies]
clap = "2.20"

[build-dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_yaml = "0.8"
cc = "1.0"